/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiMoviesIdRouteImport } from "./routes/api/movies.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMoviesIdRoute = ApiMoviesIdRouteImport.update({
  id: "/api/movies/$id",
  path: "/api/movies/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/movies/$id": typeof ApiMoviesIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/movies/$id": typeof ApiMoviesIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/movies/$id": typeof ApiMoviesIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/api/movies/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/movies/$id";
  id: "__root__" | "/" | "/api/movies/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiMoviesIdRoute: typeof ApiMoviesIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/movies/$id": {
      id: "/api/movies/$id";
      path: "/api/movies/$id";
      fullPath: "/api/movies/$id";
      preLoaderRoute: typeof ApiMoviesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMoviesIdRoute: ApiMoviesIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
